### ISSUE TITLE
Experiment detail page

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#104]
## Description
This page will show the results of an experiment. This will include ML plots and FI plots as well as the logs from the run.

## Tasks
- [x] Create page
- [x] Dropdown selector for experiment to view
- [x] Render logs expander
- [x] Render ml and fi plot expanders
- [x] Test
