### ISSUE TITLE
Options refactor

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#109]
## Description
Currently we are using old options classes based on the CLI. There's a lot of coupling of some options to either the ML or FI pipelines. To make this work with the new multi-page layout, where the ML and FI pipelines can be independently run, we need to separate the concerns of the options classes more and migrate away from the old CLI style options classes.

## Tasks
- [x] Make plotting options in `biofefi.options.plotting`
- [x] Move data path from `MLOptions` to `biofefi.options.execution`
- [x] Move normalisation from `MLOptions` to `biofefi.options.execution`
- [x] Use `biofefi.options` options classes in ML pipeline
- [x] Use `biofefi.options` options classes in FI & Fuzzy pipelines
- [x] Delete `biofefi.machine_learning.ml_options`
- [x] Delete `biofefi.feature_importance.feature_importance_options`
- [x] Delete `biofefi.feature_importance.fuzzy_options`
