### ISSUE TITLE
Fix navigation error

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#115]
## Description
When attempting to run pipelines, streamlit's page links throw an error where they cannot resolve the paths. This is not a problem when loading the app and navigating the pages, however. A quick solution is to use streamlit's built in navigation. Another option is to look at [`st.navigation`](https://docs.streamlit.io/develop/api-reference/navigation/st.navigation). The only problem is this is less aesthetically pleasing. But obviously that's preferable to not being able to run the pipelines.

## Tasks
- [x] Remove the `navbar` component from all the pages
- [x] Investigate `st.navigation`
  - [x] Failing that, turn on streamlit's default navigation sidebar
    - [x] Rename page files so their names look nice in the navbar
- [x] Test
