### ISSUE TITLE
FI pipeline doesn't run due to missing config key

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#116]
## Description
After sorting the page navigation and testing the pipeline pages, it turns out the FI pipeline won't run as the key for saving plots is never configured on the page. There are 2 solutions: 
1. add a widget to the page with the configuration enum as the key, or
2. the outputs are sort of the point of BioFEFI, maybe they should just always be saved?

## Tasks
If using 1.
- [ ] Add a widget to capture if the user wants to save FI and Fuzzy plots
- [ ] Put the "save output" options at the bottom of the page before the run button, like in "Train Models" page.

If using 2.
- [ ] Remove the widgets for saving outputs from all the pipeline pages
- [ ] Set any option relating to saving outputs to true in the `build_configuration` functions on the pipeline pages

In either case
- [ ] Test
