### ISSUE TITLE
LIME plots are causing the function that saves feature importance plots to crash

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#119]
## Description
Using the LIME local feature importance doesn't produce a plot. An error in the pipeline process is thrown instead. This is due to the shape of the data frame being plotted having the wrong dimensions and column names. This results in a `KeyError` when trying to build the LIME local importance plot.

## Tasks
- [x] Find out why LIME and SHAP data frames have different shapes
- [x] Is there a more generic way of making FI plots that will be compatible with the way we plot FI
- [x] If so, implement it.
