### ISSUE TITLE
Check if a user wants to re-run ML training

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#127]
## Description
The app should check if an experiment already has machine learning models and ask the user if they want to overwrite existing models in a experiment. If not, direct them to the "New Experiment" page.

## Tasks
- [x] Check for the existence of ML models folder and that there are models in that folder
- [x] If there are, warn the user there are models and ask if they want to delete them.
- [x] If delete, clear the model folder and the plots and logs folder and re-run the pipeline
- [x] Tests
