### ISSUE TITLE
Check if a user wants to re-run FI

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#128]
## Description
The app should check if a user has already performed FI and ask the user if they want to overwrite existing outputs in an experiment. If not, direct them to the "New Experiment" page.

## Tasks
- [x] Check for the existence of FI outputs (plots, results, logs, etc) and that those folders aren't empty
- [x] If there are outputs, warn the user there are outputs and ask if they want to delete them.
- [x] If delete, clear the outputs (plots and logs folder, etc) and re-run the pipeline
- [x] Tests
