### ISSUE TITLE
Running Fuzzy post options refactor

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#131]
## Description
While trying to run the fuzzy analysis with the refactored options, I found that fuzzy does not work without running ensemble and local feature importance analyses. In the course of trying to run the local feature importance, I found a bug in both LIME (already captured in <insert issue>) and local SHAP (captured in <create and reference issue here>) which prevent getting to the fuzzy. Once these are solved, one solution could be 1) that the user can't see the fuzzy configurations until they have configured ensemble and local FI. While these are not configured, show the instructions to configure these FIs. Another could be 2) fuzzy should use the importance that is actually computed. It could use one in preference to another if multiple are used.

## Tasks
In case of 1)
- [ ] If local and ensemble FI are not configured, show a message telling the user to configure them if the check the box to do fuzzy

In case of 2)
- [ ] Find out what the preferred FI for doing fuzzy is.
- [ ] Check which FI has been ran and use that. If multiple FIs are produced, use the preferred one.

In either case
- [ ] Test
