### ISSUE TITLE
Set-up documentation site

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#149]
## Description
It would be nice to have a documentation site available via github pages that users and developers can look at. Users would be able to use it as a manual for the site. Developers would be able to look up documentation about the code.

## Tasks
- [x] Setup a docs folder in the repo
- [x] Generate docs for code
- [x] Workflow to publish to GH pages
