### ISSUE TITLE
Table for metrics of each bootstrap

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#152]
## Description
We would like a table of metrics for each bootstrapped model on the UI on the ML page upon completion and on the View Experiments page

## Tasks
- [ ] For regression we want: R2, MAE, and RMSE (get avg and std of each metric)
- [ ] For classification show sensitivity, specificity, F1 score and G score (geometric_mean_score) (avg and std)
- [ ] display them on the above pages
