### ISSUE TITLE
Check which bootstrap is being plotted

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#153]
## Descriptions
Currently we don't which model bootstrap is being shown on the UI. We want to find the average R2 first. Then we want to find the model whose R2 is closest to the average. Then we use that model to produce the actual vs predicted plots.

## Tasks
- [x] Find average R2 of all the bootstraps for a model
- [x] Find the model whose R2 is closets to the average R2
- [x] Use that to make the actual vs predicted plot and show that plot to the user (and save it of course)
- [x] Test
