### ISSUE TITLE
Create a data visualisation tab

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#162]
Currently, the app does not allow to analyse the input data. To fix this, a data visualisation page has to be created.
## Tasks
- [x] Create the data visualisation tab.
- [x] Within this tab, create plots such as: distribution of the target variable (histogram and/or kernel density estimation).
- [x] Analysis of the independent variables, such as: correlation matrix, correlation plots.
- [ ] Test
