### ISSUE TITLE
Random forest parameters to match `sklearn`

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#169]
## Description
The default parameters in `biofefi` for `RandomForest` models don't match those of the documentation. Also `n_estimators` can't be `None` like in the docs.

## Tasks
- [ ] Check which parameters don't default to the `sklearn` defaults
- [ ] Make them match the docs
- [ ] Allow `n_estimators` to be `None`
- [ ] Test
