### ISSUE TITLE
Add BRNNs to the front-end

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#173]
## Description
Now that BRNNs have been added to the code, we can give users the options to train them.

## Tasks
- [ ] On the Train Models page, add the option to train BRNNs.
- [ ] Add configurable hyper-parameters to the page.
- [ ] Pass the options to the backend
- [ ] Test
