### ISSUE TITLE
Make plots on data viz page use the style the user configured on the new experiment page

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#174]
## Description
The plots on the data visualisation page don't use the style configured by the user on the new experiment page. We should import those settings and apply them to these plots.

## Tasks
- [ ] Add plot options param to plot forms
- [ ] load the options on the data viz page and pass to forms
- [ ] update params and docstring of the forms to have type annotations
- [ ] Test
