### ISSUE TITLE
Implement Grid Search

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#179]
## Description
We need to determine which hyper-parameters to put in the grid search for each model and a list of possible values for each one. We should research each of our available models and determine which are the simplest to perform a grid search on. Then we need to produce a grid for each of the models. Then we need a way to perform the grid search. We will use [`GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#gridsearchcv) from `sklearn`. This will perform cross-validation for us, as well. Its output is the best model from CV. We can also get the metrics from all the splits too. We will not be producing bootstrapped data sets grid search, as this is managed by the `GridSearchCV` class.

## Tasks
- [x] Create search grids for each model we offer
  - Research the available HPs and determine which ones to put in the grid 
- [x] Create a function to perform grid search
- [x] Save the best model
- [x] Save the metrics for the best model
