### ISSUE TITLE
Grid search backend changes

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#180]
## Description
We need to determine how the user is training a model. Either with manual parameter setting or using grid search. Then we need to prepare the data accordingly and set of the model training.

## Tasks
- [x] Handle if the user is manually training a model or using grid search to determine how to prepare the data 
- [x] Pass manual params to model if using manual
- [x] Pass grids to the grid search model if using Grid Search
