### ISSUE TITLE
Execute the pipeline from the UI

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#23]
## Description
Currently the UI can't execute the pipeline. It needs to receive a data file from the user and run the pipeline, as configured in the UI. The run should be cancellable by a button in the UI.

## Tasks
- [x] Handle file uploading
- [x] Callback for running the pipeline with the desired configuration
- [x] Run should be cancellable
