### ISSUE TITLE
Configurable dependent variable

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#24]
## Description
Currently the pipeline defaults to the last column in the data to select the dependent variable. It would be helpful to be able decide which column to use by name.

## Tasks
- [x] Add dependent variable option to UI
- [x] Add dependent variable option to CLI
- [x] Implement dependent variable selection in the pipeline
