### ISSUE TITLE
Displaying logs in the UI

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#37]
## Description
The UI needs to show the logging outputs so the user can see how far the pipeline has progressed.

## Tasks
- [x] Add a text box to the UI to display the logs from the most recent run
- [x] Save logs to a sensible area
  - nest by experiment name and date?
- [x] add to UI config
