### ISSUE TITLE
Upload pre-trained models or model parameters

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#49]
## Description
Currently the app must train machine learning models from scratch each time. We can point to a folder containing ml models and load them in to be evaluated

## Tasks
- [x] add field for uploading pre-trained models
- [x] load those models in
- [x] assess them with FI and Fuzzy
