### ISSUE TITLE
Update README.md to show how to use the UI

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#72]
## Description
Update the README to discuss installation and use of the UI.

## Tasks
- [x] Describe installation
- [x] Describe how to run the app
- [x] Describe the machine learning options
- [x] Describe where to find outputs
