### ISSUE TITLE
Feature importance plots and results are not saved in the experiment directory like ML plots

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#73]
## Description
Machine learning plots are saved in `$BASE_DIR/<experiment name>/ml/plots`. The directories for saving feature importance and fuzzy plots/results is determined in `feature_importance.call_methods.save_importance_results`. This is not configurable currently and it would be preferable for the save path to be passed to this function. It is also unclear if the UI is saving the plots at all.

## Tasks
- [x] Alter `feature_importance.call_methods.save_importance_results` so the save path can be configured.
- [x] Save the plots under the experiment directory
- [x] Investigate if the plots are being generated at all
- [x] Make necessary changes to address the plots not being made, if so.
- [x] Test
