### ISSUE TITLE
Update package management

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#77]
## Description
BioFEFI needs to be packaged in a way that handles the minimum required python (3.11) and fixes dodgy dependencies. For example, numpy is pinned to 1.26.0 but that is not available. The project also needs to be packaged up for easier installation. The  README requires updating to show how to install python.

## Tasks
- [ ] Fix `numpy` to an applicable patch of 1.26
- [ ] Add to `README.md` instructions for installing python, with the correct version (3.11+)
- [ ] Add poetry for package/dependency management
