### ISSUE TITLE
Plot options panel

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#78]
## Description
Currently options for how plots look are only available on the feature importance tab. These are actually more general and can go in their own tab and be applied to other plots that aren't made as part of FI analyses.

## Tasks
- [x] Extract options to do with plotting into their own tab.
- [x] Create options class for plotting options
- [x] Pass the plotting options to the relevant places
