### ISSUE TITLE
Main/landing page

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#82]
## Description
A landing page for BioFEFI. This should have a description of the app and what it can do. It should link to another page to create an experiment.

## Tasks
- [x] Create the page
- [x] Add logo at the top
- [ ] Add description of the app's functions
- [x] Link to experiment creation page
