### ISSUE TITLE
Experiment creation page

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#83]
## Description
A page where users can set up an experiment. The user can give it a name which will be used to create a subdirectory in `$HOME/BioFEFIExperiments`. Once created, take the user to an experiment detail page.

## Tasks
- [ ] Create the page
- [ ] Form to create the experiment
  - Experiment name
- [ ] Save to a `$HOME/BioFEFIExperiments/<experiment name>`
