### ISSUE TITLE
ML training page

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#84]
## Description
Separate the model training functionality onto a separate page. You should be able to select an experiment to associate the models with. The form should do all the same stuff as the ML options box in the current app.

## Tasks
- [x] Create the page
- [x] Take the options from the ML training dropdown and convert to a form on the new page
- [x] Dropdown listing experiments in the `BioFEFIExperiments` folder
- [x] Take the ML parts of the current pipeline and convert them to a process for this page
- [x] Test
