### ISSUE TITLE
Feature importance page

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#85]
## Description
Separate page for FI pipeline Move the FI and fuzzy options to a form on this page. Select an experiment from a dropdown populated with experiments in the `BioFEFIExperiments` directory. The user should be able to upload pre-existing models as well to be evaluated.

## Tasks
- [x] Create the page
- [x] Move options for FI to a form on this page.
- [x] Take the FI and fuzzy parts of the pipeline and create a new pipeline for just those. Spawn as a process like on the current app.
- [x] Test
