### ISSUE TITLE
Feature engineering page

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#86]
## Description
Separate page for performing feature engineering on a dataset. 

## Tasks
- [ ] Create the page
- [ ] Create the options class(es) and enum(s) for FE
- [ ] Create the pipeline
- [ ] Spawn as a process
- [ ] If not already created, create a service for retrieving an experiment to save the results to
- [ ] Test
