### ISSUE TITLE
Use streamlit fragments for UI components

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#88]
## Description
We have some functions that produce parts of the UI. These can be decorated with the streamlit fragment decorator, so that changes to these components don't cause re-rendering of the whole app.
https://docs.streamlit.io/1.36.0/develop/api-reference/execution-flow/st.fragment#stfragment

This should also help with the display changing mid run.

## Tasks
- [x] look through the components directory
- [x] decorate component functions with the fragment decorator
- [x] look for portions of the UI in `ui.py` that can be extracted into fragments and put them into fragments
- [x] test
