### ISSUE TITLE
Dummy data for testing BioFEFI

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#89]
## Description
Add a separate folder with some nice example data sets to play with. It would be nice if we had a regression set and a classification set.

## Tasks
- [ ] add a regression dataset(s)
- [ ] add a classification dataset(s)
- [ ] make sure it's included in the build by poetry (ask @dcl10)
