### ISSUE TITLE
Update README.md to show new installation and usage

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#90]
## Description
Now that BioFEFI is packaged with poetry, we need to tell users how to use it. We should also tell developers how to work with it. There should also be a note on the requirement to install OpenMP for XGBoost.

## Tasks
- [x] Show how to install BioFEFI
- [x] Show how to run BioFEFI
- [x] Show developers how to work with BioFEFI
