### ISSUE TITLE
Make the run button disabled / invisible when a pipeline is running

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#96]
## Description
The run button remains visible and enabled while the pipeline is running. This may confuse the user. It would be better if the run button vanished until the user presses cancel or the run finishes. Similarly, the cancel button remains visible when the run is finished. It should vanish when the pipeline finishes executing.

## Tasks
- [ ] Find a way to communicate if the pipeline is running to the UI
- [ ] Based on if the pipeline is running, hide the run button
- [ ] Hide the cancel button once the pipeline is finished
