### ISSUE TITLE
Plot colour schemes and fonts

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#97]
## Description
We want the users to be able to set the colour scheme for the plots. We can add a dropdown with choices of known colour schemes in matplotlib (for example). Fonts should also be selectable. We can also set the axes text size and title text size separately.

## Tasks
- [x] Find out what colour schemes are available
- [x] Find out what fonts are available
- [x] Add drops downs for fonts and colour schemes
- [x] Capture this from the UI and pass to plotting functions
- [x] Capture size of axes labels
- [x] Capture size of title
- [x] Test
