### ISSUE TITLE
Bayesian regularised neural networks

### ISSUE THREAD

**Issue by dcl10** [Biomaterials-for-Medical-Devices-AI/BioFEFI#98]
## Description
@Grazziela shared a paper on machine learning model that we could implement. The paper can be found [here](https://link.springer.com/protocol/10.1007/978-1-60327-101-1_3). There is some python code already for the model which can be converted into a scikit-learn model to make it compatible with the pipelines we already have. We should read the paper to see if the methodology is suitable for classification, regression or both.

Some useful pages on the scikit-learn site are:
- https://scikit-learn.org/1.5/modules/generated/sklearn.base.BaseEstimator.html
- https://scikit-learn.org/1.5/modules/generated/sklearn.base.ClassifierMixin.html
- https://scikit-learn.org/1.5/modules/generated/sklearn.base.RegressorMixin.html

## Tasks
- [x] Read the paper
- [x] Review the python code for BRN networks
- [x] If suitable, produce a classifier based on scikit-learn
- [x] If suitable, produce a regressor based on scikit-learn
- [x] Test

**Comment by Karthi-DStech** [comment]
Hi @dcl10,
I hope you're doing well.

We’ve completed the backend scripts for the Bayesian Regularised Neural Network and Synthetic Data Creation, and I wanted to discuss the next steps. Could we schedule a short discussion at your convenience to align on how to proceed further?

Looking forward to your thoughts.

Thanks and regards,
Karthik
